name: Cypress Tests

on: [pull_request,workflow_dispatch]

env:
  ADOBE_EDGE_URL: 'https://${{ github.head_ref || github.ref_name }}--adobe-edge--visualcomfort.hlx.page'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: ${{ env.ADOBE_EDGE_URL }}
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_BASE_URL: ${{ env.ADOBE_EDGE_URL }}